_target_: src.models.epic_jedi.EpicDiffusionGenerator

ema_sync: 0.999
loss_name: huber
mle_loss_weight: 0.001
sampler_name: euler
sampler_steps: 50

epic_jedi_config:
  hid_d: 128
  equiv_layers: 6
  latent: 16

cosine_config:
  outp_dim: 32
  min_value: 0
  max_value: 1
  frequency_scaling: exponential

diff_config:
  max_sr: 0.999
  min_sr: 0.02

normaliser_config:
  max_n: 2000_000

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0001
