# @package _global_

defaults:
  - hydra: default.yaml
  - paths: default.yaml
  - _self_

sampler_steps:
  - 200
  # - 100
  # - 200
  # - 50
  # - 20
  # - 40
  # - 60
  # - 80
  # - 100

sampler_name:

  - em

load: best

project_name: pc_jedi_150
network_name: 2023-05-19_11-01-28-016315

