# @package _global_

defaults:
  - hydra: default.yaml
  - paths: default.yaml
  - _self_

sampler_steps:
  - 100
  - 200
  - 50
  - 20
  # - 40
  # - 60
  # - 80
  # - 100

sampler_name:
  - ddim
  - em
  - euler

load: best

project_name: epic_jedi_30
network_name: 2023-05-19_10-03-09-602489

