# @package _global_

defaults:
  - hydra: default.yaml
  - paths: default.yaml
  - _self_

datamodule:
  _target_: src.datamodules.flow_gen.FlowGeneratedData
  flow_path: /srv/beegfs/scratch/users/s/senguptd/jet_diffusion/epic_flow_learning/top__pt_M_N__given__ID_150f/
  ctxt_vars:
    - pt
    - mass
    # - num_particles
    # - type
  data_conf:
    jet_type:
      - t
    num_particles: null
    one_hot: False
  batch_size: 2048

sampler_steps:
  # - 200
  - 200
  - 50
  - 100

sampler_name:
  - em
  - euler
  - ddim
  - rk
  - midpoint

load: last

project_name: final_cedric_changes
network_name: 2023-07-10_18-56-53-293584
