# @package _global_

defaults:
  - hydra: default.yaml
  - paths: default.yaml
  - _self_

sampler_steps:
  # - 200
  - 100
  - 200
  - 50
  - 20
  - 40
  - 60
  - 80
  # - 100

sampler_name:
  - em
  - euler
  - ddim
  - rk

load: last

project_name: epic_jedi1_c
network_name: null

