_target_: src.datamodules.jetnet.JetNetDataModule

data_conf:
  n_jets: null
  high_as_context: True
  recalculate_jet_from_pc: False
  jet_type: t
  data_dir: ${paths.data_dir}
  num_particles: 150
  split_fraction: [0.9, 0.0, 0.1]
  particle_features:
    - etarel
    - phirel
    - ptrel
  jet_features:
    - pt
    - mass
  log_squash_pt: True

loader_kwargs:
  pin_memory: true
  batch_size: 256
  num_workers: 2
  drop_last: True
